# .pre-commit-config.yaml
# DevSecOps baseline pre-commit configuration
# Ensures security + hygiene before every commit
# Excludes OWASP Juice Shop (intentionally vulnerable)

repos:
  # --- Core pre-commit checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: ^app/juice-shop/
      - id: check-json
        exclude: ^app/juice-shop/
      - id: end-of-file-fixer
        exclude: ^app/juice-shop/
      - id: trailing-whitespace
        exclude: ^app/juice-shop/
      - id: detect-private-key
        exclude: ^app/juice-shop/
      - id: check-added-large-files
        exclude: ^app/juice-shop/

  # --- Secret scanning ---
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks
        args:
          - "--redact"
          - "--config=.gitleaks.toml"

  # --- Dockerfile linting ---
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        files: ^Dockerfile
