# .pre-commit-config.yaml
# DevSecOps baseline pre-commit configuration
# Ensures security + hygiene before every commit

repos:
  # --- Core pre-commit checks ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0   # latest stable
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files

  # --- Secret scanning ---
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0  # current release
    hooks:
      - id: gitleaks
        args: ["--redact"]   # redact secrets in output

  # --- Dockerfile linting ---
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.1-beta  # latest patch
    hooks:
      - id: hadolint
        name: Lint Dockerfiles
        files: ^Dockerfile

# --- Optional: Container & Dependency scanning ---
# These are heavy scans, so leave commented unless you want them
# before *every* commit. They already run in CI/CD pipeline.
#
#  - repo: local
#    hooks:
#      - id: trivy-fs-scan
#        name: Trivy FS Scan
#        entry: trivy fs .
#        language: system
#        types: [file]
#
#      - id: snyk-test
#        name: Snyk Security Test
#        entry: snyk test
#        language: system
#        pass_filenames: false
