name: Secure DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  # ---------------------------
  # Commit Stage – Hygiene & Tests
  # ---------------------------
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pre-Commit
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Run Unit Tests
        run: |
          cd app
          npm install
          npm test

  # ---------------------------
  # Security Stage – SAST / SCA / IaC / Container
  # ---------------------------
  security-stage:
    runs-on: ubuntu-latest
    needs: commit-stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Snyk SCA
        uses: snyk/actions/node@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Checkov (IaC Scan)
        run: |
          pip install checkov
          checkov -d iac/

      - name: Run Trivy (Container Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:ci
          format: table

      - name: Generate SBOM (Syft)
        uses: anchore/syft-action@v0.15.0
        with:
          image: ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:ci
          output-file: pipelines/security-reports/sbom.json

  # ---------------------------
  # Build & Deploy Stage
  # ---------------------------
  build-deploy:
    runs-on: ubuntu-latest
    needs: security-stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
          -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:${{ github.sha }} ./app
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:${{ github.sha }}

      - name: Terraform Deploy
        run: |
          cd iac
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

  # ---------------------------
  # Post-Deploy Stage – DAST / Policy
  # ---------------------------
  post-deploy:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: https://nao-juice-shop.azurewebsites.net

      - name: Azure Policy Compliance Check
        run: |
          az policy state summarize \
            --subscription ${{ secrets.SUBSCRIPTION_ID }} \
            --query "summaryResults"
