name: Secure DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ "main", "Devsec-01" ]
  pull_request:
    branches: [ "main", "Devsec-01" ]
  workflow_dispatch:

permissions:
  contents: read   # ✅ Restrict default GITHUB_TOKEN permissions

jobs:

  # ---------------------------
  # Commit Stage – Hygiene Only
  # ---------------------------
  commit-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Pre-Commit and Run Hooks
        run: |
          pip install pre-commit
          pre-commit run --all-files

      - name: Skip Unit Tests
        run: echo "Skipping Juice Shop unit tests (intentionally vulnerable)."

  # ---------------------------
  # Security Stage – SAST / SCA / IaC / Container
  # ---------------------------
  security-stage:
    runs-on: ubuntu-latest
    needs: commit-stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create reports directory
        run: mkdir -p pipelines/security-reports

      - name: Install Dependencies
        working-directory: app/juice-shop
        run: npm install --legacy-peer-deps

      - name: Run Snyk SCA
        uses: snyk/actions/node@master
        with:
          command: test
          args: --file=app/juice-shop/package.json --org=cloudfred1010 --json-file-output=../../pipelines/security-reports/snyk-sca.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Run Checkov (IaC Scan)
        working-directory: ${{ github.workspace }}/iac
        run: |
          pip install checkov==3.2.467
          checkov -d . -o json > ../pipelines/security-reports/checkov.json
        continue-on-error: true

      - name: Run Trivy (Container Scan)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:${{ github.sha }}
          format: json
          output: pipelines/security-reports/trivy.json
        continue-on-error: true

      - name: Generate SBOM (Syft)
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh \
            | sh -s -- -b /usr/local/bin
          syft ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:${{ github.sha }} -o json \
            > pipelines/security-reports/sbom.json
        continue-on-error: true

  # ---------------------------
  # Build & Deploy Stage
  # ---------------------------
  build-deploy:
    runs-on: ubuntu-latest
    needs: security-stage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Fix 1: Export Terraform Azure env
      - name: Export Azure env for Terraform
        run: |
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_ID=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJSON(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV

      # ✅ Fix 2: Use service principal creds to login to ACR
      - name: Log in to ACR
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:${{ github.sha }} ./app/juice-shop
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/juice-shop:${{ github.sha }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - name: Terraform Deploy
        working-directory: ${{ github.workspace }}/iac
        run: |
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

  # ---------------------------
  # Post-Deploy Stage – DAST / Policy
  # ---------------------------
  post-deploy:
    runs-on: ubuntu-latest
    needs: build-deploy
    steps:
      - name: Run OWASP ZAP Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: https://nao-juice-shop.azurewebsites.net
        continue-on-error: true

      - name: Azure Policy Compliance Check
        run: |
          az policy state summarize \
            --subscription ${{ secrets.SUBSCRIPTION_ID }} \
            --query "summaryResults"
        continue-on-error: true
